### ISSUE TITLE
Is it possible to mute the BEL character?

### ISSUE THREAD

**Issue by sedwards2009** [rprichard/winpty#147]
In other words is it possible to prevent the hidden console from playing the bell sound when it gets a BEL character?

**Comment by rprichard** [comment]
I'm not sure what winpty could do to disable the console's BEL sound. It has a mode for pre-Win7 that places the console onto a background desktop, so I thought that might work (e.g. `WINPTY_DEBUG=force_desktop`), but I tried that, and I still hear beeping.

If the problem is bash, maybe you could add `set bell-style none` to `~/.inputrc` or `/etc/inputrc` (https://stackoverflow.com/a/36726662/4613163). I think that will disable it for any readline-based program.

**Comment by sedwards2009** [comment]
Thanks for the quick response. I'll pass your suggestion about `.inputrc` along to the original reporter on my side.
