### ISSUE TITLE
Ability to fetch current working directory for spawned process

### ISSUE THREAD

**Issue by segrey** [rprichard/winpty#158]
It'd be great to be able to fetch spawned process's current working directory via winpty API.
That would allow to persist working directory in IntelliJ Terminal between IDE restarts.

**Comment by segrey** [comment]
Fetching working directory for winpty-agent.exe doesn't work (tried and failed).

**Comment by rprichard** [comment]
I'd prefer that this functionality live outside of winpty. The only thing it needs from winpty is the handle of the spawned process, which is provided by the `winpty_spawn` API:

```c++
/*
 * ...
 * On success, the function returns TRUE.  For each of process_handle and
 * thread_handle that is non-NULL, the HANDLE returned from CreateProcess is
 * duplicated from the agent and returned to the winpty client.  The client is
 * responsible for closing these HANDLES.
 * ...
 */
WINPTY_API BOOL
winpty_spawn(winpty_t *wp,
             const winpty_spawn_config_t *cfg,
             HANDLE *process_handle /*OPTIONAL*/,
             HANDLE *thread_handle /*OPTIONAL*/,
             DWORD *create_process_error /*OPTIONAL*/,
winpty_error_ptr_t *err /*OPTIONAL*/);
```

pty4j already has the child process handle in `WinPty.myProcess`.

My reasons for not wanting to include it:
 - It's digging into Windows internals.
 - It's reading another process' memory, which I suspect could trigger antivirus programs.
 - It uses the handle for the spawned process, but suppose the user runs a subshell (e.g. powershell-under-cmd)? Maybe the IDE wants to look for subprocesses of the spawned process then.

Aside: It looks like the `IsWow64Process(GetCurrentProcess(), &wow)` call fails if the *agent* process is WOW64, rather than the agent's child process. Assuming that's correct, there are a couple of consequences:
 - For this API to work, `winpty.dll` needs to always launch an agent process with the proper architecture for the OS, so someone redistributing a 32-bit version of `winpty.dll` generally needs to include both 32-bit and 64-bit copies of the agent. I've been thinking of doing something similar for https://github.com/rprichard/winpty/issues/46.
 - I'm looking at adding a ConPTY backend, and currently I'm hoping to avoid launching an agent process when using ConPTY, but if there's no agent, this functionality would need to live in `winpty.dll`, which could be in a WOW64 process.

**Comment by segrey** [comment]
@rprichard Thanks for looking into it! Very true, this functionality can live outside of winpty. Unfortunately, it depends on Windows internals and it might trigger antivirus programs (thanks for pointing out, need to check).
Regarding `IsWow64Process`, it allows to prevent reading 64-bit process memory from 32-bit process (https://stackoverflow.com/questions/7446887/get-command-line-string-of-64-bit-process-from-32-bit-process).
BTW, out of curiosity, would you advice to implement this functionality using `CreateRemoteThread` + `GetCurrentDirectory` in context of the target process or keep the current approach?
If the current one is more preferred, would it be better to place this functionality in a dll or in a separate executable file?
Closing the issue and the PR.
