### ISSUE TITLE
does libwinpty has a way to detect cmd.exe needs a input？

### ISSUE THREAD

**Issue by xspeed1989** [rprichard/winpty#199]
I want to develop a remote shell like ssh, but I don't how to detect cmd.exe needs a input,
I can only read a stream of bytes from the pipe, but can't tell if input is currently required。

**Comment by andry81** [comment]
To detect the input, you have to consume the input instead of `cmd.exe` and push it to the `cmd.exe` stdin. But that will require a pipe which will turn off `cmd.exe` interactivity, because `cmd.exe` checks the type of stdin/stdout handles and if `GetStdHandle(STD_INPUT_HANDLE) != FILE_TYPE_CHAR` or `GetStdHandle(STD_OUTPUT_HANDLE) != FILE_TYPE_CHAR` then, `cmd.exe` turns off interactive input (TAB completion, cursor buttons history traverse, etc).
Another implementation would be a code injection into `cmd.exe` process to intercept the `ReadConsole` API.

**Comment by xspeed1989** [comment]
> To detect the input, you have to consume the input instead of `cmd.exe` and push it to the `cmd.exe` stdin. But that will require a pipe which will turn off `cmd.exe` interactivity, because `cmd.exe` checks the type of stdin/stdout handles and if `GetStdHandle(STD_INPUT_HANDLE) != FILE_TYPE_CHAR` or `GetStdHandle(STD_OUTPUT_HANDLE) != FILE_TYPE_CHAR` then, `cmd.exe` turns off interactive input (TAB completion, cursor buttons history traverse, etc). Another implementation would be a code injection into `cmd.exe` process to intercept the `ReadConsole` API.

OK, Thanks, 
I think I should not focus this case,I should
send key event to winpty-agent then wait msg, use recived msg to render text is a correctly way.
