### ISSUE TITLE
ANSI escape sequences in captured output

### ISSUE THREAD

**Issue by magixx** [rprichard/winpty#35]
Using cygwin and python/plumbum I am noticing that I'm getting [ANSI escape sequences](http://stackoverflow.com/questions/15011478/ansi-questions-x1b25h-and-x1be) in my output such as '\x1b[?25l\r\x1b[2K\x1b[0m\r\n\x1b[2K'. Is there a way to hide this reliably? I've not notice any such issue with [proxywinconsole](http://sergeybelous.com/SHELL-TERMINAL.html).

**Comment by rprichard** [comment]
I'm curious as to why you need to suppress the ANSI escape sequences.  Normally they're interpreted by a terminal emulator, so you don't see them.

There is a "console mode" in libwinpty that suppress some/all sequences, but IIRC, there's no way to enable it from `console.exe`.  I'm not sure what it's intended use is.  (I didn't probe very much when it was contributed.)

winpty uses cursor-up and erase-line commands to backtrack in the terminal when parts of the console change.  (e.g. full-screen editors, progress bars, REPLs).  I'm not sure how winpty is useful if those commands are suppressed.

**Comment by rprichard** [comment]
Can you explain what you're doing where you're seeing the unwanted escape sequences?

winpty does output a lot of escape sequences, and some of them can be suppressed:
 * If you aren't interested in e.g. colors or cursor position/visibility, then winpty can have a flag for disabling that information.
 * winpty can be smarter about appending to the current line.  Currently, it always redraws lines from scratch, and it resets the cursor position before doing so.

If you absolutely cannot tolerate any escape sequences, then winpty has a "console mode" that's relevant, but all that does now is suppress escape sequences, so in principle, it can output a lot of junk.

I need more information to do anything with this issue; otherwise, I'll just close it.

**Comment by rprichard** [comment]
I'm not sure what this issue is about.  winpty is designed to output escape sequences normally.  The console mode in master is much improved now.  The `winpty.exe` adapter has an undocumented `-Xplain` switch you can use to see what console mode would output.

I'm going to close this issue.

**Comment by jagannatharjun** [comment]
I needed to catch child's input and output and using winpty for unbuffered io from child
I am using a slightly modified version of this
winpty\src\tests\trivialtest.cc:
```
static std::vector<unsigned char> filterContent(
        const std::vector<unsigned char> &content) {
    std::vector<unsigned char> result;
    auto it = content.begin();
    const auto itEnd = content.end();
    while (it < itEnd) {
        if (*it == '\r') {
            // Filter out carriage returns.  Sometimes the output starts with
            // a single CR; other times, it has multiple CRs.
            it++;
        } else if (*it == '\x1b' && (it + 1) < itEnd && *(it + 1) == '[') {
            // Filter out escape sequences.  They have no interior letters and
            // end with a single letter.
            it += 2;
            while (it < itEnd && !isalpha(*it)) {
                it++;
            }
            it++;
        } else {
            // Let everything else through.
            result.push_back(*it);
            it++;
        }
    }
    return result;
}

```

is there any other way to do it from winpty.exe
