### ISSUE TITLE
winpty hangs when launching docker

### ISSUE THREAD

**Issue by elebeaup** [rprichard/winpty#54]
When attempting to run docker in debug mode on Cygwin with the following command, the console hangs when exiting :
```
console docker -D run -it busybox
/ # exit
```

On windows (command prompt), all is ok.
```
 docker -D run -it busybox
/ # exit
DEBU[0002] [hijack] End of stdout
DEBU[0002] [hijack] End of stdin
DEBU[0002] Couldn't send EOF: use of closed network connection
DEBU[0002] End of CmdRun(), Waiting for hijack to finish.
```

In cygwin, debug log doesn't appear and console hangs. It is not possible to interrupt (ctrl+c) the process.

I notice no issue in normal mode (without the flag -D).

**Comment by rprichard** [comment]
So far, I can't reproduce the problem.  I tried:
 * Windows 7 64-bit
 * Docker version 1.8.3, build f4bf5c7
 * docker-machine version 0.4.1 (e2c88d6)
 * 64-bit Cygwin, cygwin1.dll 2.2.1
 * winpty compiled using mingw-w64, commit 3b73576ab9

The Docker Toolbox I downloaded included MSYS Git, which bundled mintty and winpty (`console.exe` is renamed to `winpty.exe`).  FWIW, this older version of winpty responds to `WINPTYDBG=1` rather than `WINPTY_DEBUG=1`.  It still works with a recent `winpty-debugserver.exe`, though.

Here's what I saw with a recent Cygwin winpty build:

```
rprichard@ryan ~/proj/winpty
$ build/console.exe docker -D run -it busybox
time="2015-10-16T23:07:21-05:00" level=debug msg="Trusting certs with subjects: [0\x141\x120\x10\x
06\x03U\x04\n\x13\trprichard]"
/ # time="2015-10-16T23:07:21-05:00" level=debug msg="[windows] HandleOutputCommand: 0x1B5B4A \"J\
" (\"\")"

/ # echo FOO
FOO
/ # exit
time="2015-10-16T23:07:27-05:00" level=debug msg="[hijack] End of stdout"
time="2015-10-16T23:07:27-05:00" level=debug msg="[hijack] End of stdin"
time="2015-10-16T23:07:27-05:00" level=debug msg="End of CmdRun(), Waiting for hijack to finish."


rprichard@ryan ~/proj/winpty
$
```

I see the same output with `winpty docker -D run -it busybox` in the "Docker Quickstart Terminal."

What OS are you using, and is it 32-bit or 64-bit?  What version of winpty are you using?  Does `console` work with other commands like Powershell?

**Comment by elebeaup** [comment]
Sorry but i can't reproduce anymore. I have upgraded docker from 1.7 to 1.8.3. I don't know if it is due to this, but now it works.
