### ISSUE TITLE
cmd.exe prints "Not enough storage is available to process this command."

### ISSUE THREAD

**Issue by aleherb** [rprichard/winpty#74]
On some Windows 7 hosts we see the following error printed in the console window if cmd.exe is run under control of winpty-agent.exe:
`Not enough storage is available to process this command.
`

It is unclear why this happens on some hosts and not on others, but we found that it is caused by setting the console title to an empty string. The error is just cosmetic, though, there is no functional impact, AFAICT.
On hosts where this happens, it can also be reproduced independent of winpty by running a batch script using the start command with an empty title string:
`start "" /w script.bat
`

The suggested fix/workaround is to set the initial console title to e.g. a single space instead.

**Comment by rprichard** [comment]
I've seen that error before but never figured out the cause.  It always reproduced for me when I invoked winpty from a Cygwin SSH connection.  I just tried it again, and setting the title to a single space fixes the problem.  A single space seems reasonable enough.  I'll have this fixed fairly soon.  Thanks for figuring it out!

I wonder if this problem reproduces on other OSs.  I noticed [some problems](https://github.com/rprichard/win32-console-docs/blob/d1137bad611962171def8afadd2e0e849baabbf5/src/Test_GetConsoleTitleW.cc) with the `GetConsoleTitle` API in different Windows versions, so maybe that's related.

**Comment by eladkarako** [comment]
<em>First, let me apologize for reviving this old horse...</em>

I don't know if it matters to anyone anymore but WinPython had some more information 
about this issue, in one of its test-files <sub>(<code>Python/python-3.6.3/Lib/site-packages/theano/tests/run_tests_in_batch.py</code>)</sub> 

..just FYI.

<pre><blockquote>
One reason to use this script is if you are a Windows user, and see errors like
"Not enough storage is available to process this command" when trying to simply
run `nosetests` in your Theano installation directory. <strong>This error is apparently
caused by memory fragmentation: at some point Windows runs out of contiguous
memory to load the C modules compiled</strong> by Theano in the test-suite.

By using this script, nosetests is <strong>run on a small subset (batch)</strong> of tests until
all tests are run. Note that this is slower, in particular because of the
initial cost of importing theano and loading the C module cache on each call of
nosetests.
</blockquote></pre>

I think this might be related to the way the module is structured,
and has nothing to do with setting the `title`,

in-fact I think what you've done here is to suppress the <code>STDERR</code> stream,
in which the message shows.

<hr/>

The real solution is (probably) handling the output streams more gingerly,
what was done in that case was breaking long operation to multiple sub-processes,
flushing the `STDOUT` and `STDERR` more frequently before and after the sub-process was executes.
<pre>
stdout.flush()
stderr.flush()
subprocess.call(......)
stdout.flush()
stderr.flush()
</pre>
